version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_DATABASE: "teste"
      MYSQL_USER: "unicap"
      MYSQL_PASSWORD: "123"
    networks:
      - backend

  springboot:
    build:
      context: ./app
    container_name: springboot
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mariadb://mariadb:3306/teste"
      SPRING_DATASOURCE_USERNAME: "unicap"
      SPRING_DATASOURCE_PASSWORD: "123"
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: "org.mariadb.jdbc.Driver"
      SPRING_JPA_DATABASE-PLATFORM: "org.hibernate.dialect.MariaDBDialect"
      SPRING_JPA_HIBERNATE_DDL-AUTO: "update"
      SPRING_JPA_SHOW-SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.MariaDBDialect"
    depends_on:
      - mariadb
    networks:
      - backend

networks:
  backend:
